"""'Init'

Revision ID: 51c6c41b8d61
Revises: 
Create Date: 2024-05-06 18:29:33.276359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c6c41b8d61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('teachers',
    sa.Column('teachers_id', sa.Integer(), nullable=False),
    sa.Column('teachers_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('teachers_id')
    )
    op.create_table('students',
    sa.Column('students_id', sa.Integer(), nullable=False),
    sa.Column('students_name', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('students_id')
    )
    op.create_table('subjects',
    sa.Column('subjects_id', sa.Integer(), nullable=False),
    sa.Column('subjects_name', sa.String(), nullable=False),
    sa.Column('teachers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teachers_id'], ['teachers.teachers_id'], ),
    sa.PrimaryKeyConstraint('subjects_id')
    )
    op.create_table('magazine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.students_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subjects_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazine')
    op.drop_table('subjects')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('groups')
    # ### end Alembic commands ###
